### ISSUE TITLE
Problems with read and write transactions

### ISSUE THREAD

**Issue by tpcorrea** [rftafas/hdltools#8]
I wrote a Test bench to verify the design and had problems in both read and write transactions. 
### Read

In the screenshot below, the corresponding reg_i field gets a random value and the test bench tries to read it using the axi interface. As you can see in the screenshot below, rdata does not change:

![image](https://user-images.githubusercontent.com/24911387/102991339-c5bc6080-44f7-11eb-9466-7d0b2f8bf525.png)

### Write

When the Test Bench tries to write to a register, all fields of regwrite_s get the same value, as waveforms of the screenshot below illustrate:

![image](https://user-images.githubusercontent.com/24911387/102991607-51ce8800-44f8-11eb-9a6d-1a138d259d48.png)

### Test Bench
You can get the simulation files in my personal repository (https://github.com/tpcorrea/hdltools/tree/records). The Test Bench uses VUnit and UVVM with GHDL simulator. To use UVVM, you have to compile the necessary libraries and correct the run.py file to point to the correct compiled library path.

**Comment by tpcorrea** [comment]
Simulation output:
[wave.zip](https://github.com/rftafas/hdltools/files/5734889/wave.zip)

**Comment by rftafas** [comment]
fixed on 6ba8767
